#
# mdillon/postgis seems promising.
# For now, just some basic skeleton here while we get more
# clarification about interdependencies...
#
FROM mdillon/postgis:9.6

# Put geckodriver in /usr/local/bin
RUN pushd /usr/local/bin &&\
    wget -q -N https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz &&\
    tar -xzf geckodriver-v0.11.1-linux64.tar.gz &&\
    popd


# what else ...???
