FROM mbari/stoqs-base:0.0.1

RUN yum -y install postgresql96-server &&\
    yum -y groupinstall "PostgreSQL Database Server 9.6 PGDG"

# Put geckodriver in /usr/local/bin
RUN pushd /usr/local/bin &&\
    wget -q -N https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz &&\
    tar -xzf geckodriver-v0.11.1-linux64.tar.gz &&\
    popd

RUN yum -y install deltarpm scipy mod_wsgi memcached python-memcached &&\
    yum -y install graphviz-devel graphviz-python ImageMagick postgis2_96 &&\
    yum -y install freetype-devel libpng-devel giflib-devel libjpeg-devel gd-devel proj-devel &&\
    yum -y install proj-nad proj-epsg libxml2-devel libxslt-devel pam-devel &&\
    yum -y install python-psycopg2 libpqxx-devel hdf hdf-devel freetds-devel postgresql-devel &&\
    yum -y install gdal-python mapserver mapserver-python libxml2 libxml2-python python-lxml python-pip python-devel gcc mlocate &&\
    yum -y install scipy blas blas-devel lapack lapack-devel lvm2 firefox cachefilesd &&\
    yum -y groups install "GNOME Desktop" &&\
    yum -y install fftw-devel motif-devel ghc-OpenGL-devel &&\
    # For InstantReality's aopt command referenced in doc/instructions/SPATIAL_3d.md &&\
    yum -y install freeglut luajit &&\
    wget http://doc.instantreality.org/media/uploads/downloads/2.8.0/InstantReality-RedHat-7-x64-2.8.0.38619.rpm &&\
    rpm -Uvh InstantReality-RedHat-7-x64-2.8.0.38619.rpm

# Build and install MB-System, setting overcommit_memory to wizardry mode
# NOTE: Instead of:
#    echo 1 > /proc/sys/vm/overcommit_memory
# which triggers error:
#    /bin/sh: /proc/sys/vm/overcommit_memory: Read-only file system
# and noting that in the centos:7 image such file already exists and has "1" as content,
# I'm making the instruction conditional as shown,
RUN wget -q -N ftp://ftp.ldeo.columbia.edu/pub/MB-System/mbsystem-5.5.2284.tar.gz &&\
    tar -xzf mbsystem-5.5.2284.tar.gz &&\
    cd mbsystem-5.5.2284/ &&\
    ./configure --with-otps-dir=/usr/local/OTPS2 &&\
    make -j 2 && make install &&\
    ([ "`cat /proc/sys/vm/overcommit_memory`" = "1" ] || echo 2 > /proc/sys/vm/overcommit_memory) &&\
    cd ..
# TODO: such overcommit_memory setting should probably be moved to the base image.

# TODO Mapserver should probably be in its own image so it can be launched separately.
# Build and install Mapserver
RUN wget -q -N http://download.osgeo.org/mapserver/mapserver-6.4.1.tar.gz &&\
    tar xzf mapserver-6.4.1.tar.gz &&\
    cd mapserver-6.4.1 &&\
    mkdir build &&\
    cd build &&\
    /opt/cmake/bin/cmake .. -DWITH_FRIBIDI=0 -DWITH_CAIRO=0 -DWITH_FCGI=0 -DCMAKE_PREFIX_PATH="/usr/local;/usr/pgsql-9.6" &&\
    make -j 2 && make install &&\
    cp /usr/local/bin/mapserv /var/www/cgi-bin &&\
    ldconfig &&\
    cp /etc/sysconfig/httpd /etc/sysconfig/httpd.bak &&\
    echo "\
# Needed for mapserv in /var/www/cgi-bin\n\
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib64\n\
export LD_LIBRARY_PATH\n" >> /etc/sysconfig/httpd &&\
    cd ../.. &&\
    touch /tmp/mapserver_stoqshg.log &&\
    chown apache.apache /tmp/mapserver_stoqshg.log &&\
    chmod go+w /tmp/mapserver_stoqshg.log
