FROM mbari/stoqs-base:0.0.1

ARG STOQS_HOST
ARG MAPSERVER_HOST
ARG DATABASE_URL

# TODO perhaps no need to copy everything for a production env.
COPY stoqs    /opt/stoqsgit/stoqs/
COPY test.sh  /opt/stoqsgit/

ENV STOQS_HOME=/opt/stoqsgit \
    PATH=/usr/pgsql-9.6/bin:${PATH}

ENV STOQS_HOST="${STOQS_HOST}" \
    DATABASE_URL="${DATABASE_URL}" \
    MAPSERVER_DATABASE_URL="${DATABASE_URL}" \
    MAPSERVER_HOST="${MAPSERVER_HOST}"

# The following mainly as a convenience in case the container is run with bash as entry point
RUN echo "alias psql='psql --host=stoqs-postgis --port=5432'" >> /root/.bashrc

WORKDIR    /opt/stoqsgit
ENTRYPOINT ["stoqs/manage.py", "runserver", "0.0.0.0:8000", "--settings=config.settings.local"]

# TODO: Replace ENTRYPOINT with nginx/wsgi execution
