FROM centos:7

# Disable SELinux
# TODO There's no /etc/selinux/config file on the centos:7 image
#RUN sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config
RUN mkdir /selinux &&\
    echo 0 > /selinux/enforce

# Add epel, remi, and postgres repositories
RUN yum makecache fast &&\
    yum -y install wget git &&\
    yum -y install epel-release &&\
    yum -y update epel-release &&\
    yum repolist &&\
    wget -q -N http://rpms.famillecollet.com/enterprise/remi-release-7.rpm &&\
    rpm -Uvh remi-release-7*.rpm &&\
    wget -q -N https://yum.postgresql.org/9.6/redhat/rhel-7-x86_64/pgdg-redhat96-9.6-3.noarch.rpm &&\
    rpm -ivh pgdg* &&\
    yum groupinstall -y "Development Tools"

# Install Python 3.6
RUN yum install -y zlib-devel openssl-devel sqlite-devel bzip2-devel xz-libs readline-devel &&\
    yum -y install https://centos7.iuscommunity.org/ius-release.rpm &&\
    yum install -y python36u python36u-pip python36u-devel

# Install package prerequisites for NetCDF4
RUN yum -y install curl-devel hdf5 hdf5-devel

# Build and install geos
RUN echo '/usr/local/lib' >> /etc/ld.so.conf &&\
    wget -q -N http://download.osgeo.org/geos/geos-3.6.0.tar.bz2 &&\
    tar -xjf geos-3.6.0.tar.bz2 &&\
    cd geos-3.6.0 &&\
    ./configure &&\
    make -j 2 && make install &&\
    ldconfig &&\
    cd ..

# Build and install NetCDF4
RUN wget ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4.4.1.tar.gz &&\
    tar -xzf netcdf-4.4.1.tar.gz &&\
    cd netcdf-4.4.1 &&\
    ./configure &&\
    make -j 2 && make install &&\
    cd .. &&\
    export LD_LIBRARY_PATH=/usr/local/lib &&\
    wget ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-fortran-4.4.4.tar.gz &&\
    tar -xzf netcdf-fortran-4.4.4.tar.gz &&\
    cd netcdf-fortran-4.4.4 &&\
    ./configure &&\
    make -j 2 && make install &&\
    cd ..

# Build and install gdal
RUN wget -q -N http://download.osgeo.org/gdal/2.2.1/gdal-2.2.1.tar.gz &&\
    tar -xzf gdal-2.2.1.tar.gz &&\
    cd gdal-2.2.1 &&\
    export PATH=$(pwd):$PATH &&\
    ./configure --prefix=/usr/local &&\
    gmake -j 2 && gmake install &&\
    cd ..

# Download and install CMake
RUN wget -q -N http://www.cmake.org/files/v2.8/cmake-2.8.12.2.tar.gz &&\
    tar -xzf cmake-2.8.12.2.tar.gz &&\
    cd cmake-2.8.12.2 &&\
    ./configure --prefix=/opt/cmake &&\
    gmake -j 2 && gmake install &&\
    cd ..

# Build and install GMT
RUN wget -q -N ftp://ftp.iris.washington.edu/pub/gmt/gmt-5.3.1-src.tar.gz &&\
    tar -xzf gmt-5.3.1-src.tar.gz &&\
    cd gmt-5.3.1 &&\
    cp cmake/ConfigUserTemplate.cmake cmake/ConfigUser.cmake &&\
    mkdir build &&\
    cd build &&\
    /opt/cmake/bin/cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=RelWithDebInfo .. &&\
    make -j 2 && make install &&\
    cd ../..


# Build and install OSU Tidal Prediction Software
RUN pushd /usr/local &&\
    wget -q -N ftp://ftp.oce.orst.edu/dist/tides/OTPS2.tar.Z &&\
    tar -xzf OTPS2.tar.Z &&\
    cd /usr/local/OTPS2 &&\
    wget -q -N ftp://ftp.oce.orst.edu/dist/tides/TPXO8_compact/tpxo8_atlas_compact_v1.tar.Z &&\
    tar -xzf tpxo8_atlas_compact_v1.tar.Z &&\
    make extract_HC &&\
    make predict_tide &&\
    cp setup.inp setup.inp.bak &&\
    echo -e "\
DATA/Model_atlas_v1        ! 1. tidal model control file\n\
lat_lon_time               ! 2. latitude/longitude/<time> file\n\
z                          ! 3. z/U/V/u/v\n\
m2,s2                      ! 4. tidal constituents to include\n\
AP                         ! 5. AP/RI\n\
oce                        ! 6. oce/geo\n\
1                          ! 7. 1/0 correct for minor constituents\n\
sample.out                 ! 8. output file (ASCII)\n" > setup.inp &&\
    cp DATA/Model_atlas_v1 DATA/Model_atlas_v1.bak &&\
    echo -e "\
/usr/local/OTPS2/DATA/hf.tpxo8_atlas_30_v1\n\
/usr/local/OTPS2/DATA/uv.tpxo8_atlas_30_v1\n\
/usr/local/OTPS2/DATA/grid_tpxo8atlas_30_v1\n" > DATA/Model_atlas_v1 &&\
    popd

# Put geckodriver in /usr/local/bin
RUN pushd /usr/local/bin &&\
    wget -q -N https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz &&\
    tar -xzf geckodriver-v0.11.1-linux64.tar.gz &&\
    popd

RUN yum -y install nginx

RUN yum -y install deltarpm scipy mod_wsgi memcached python-memcached &&\
    yum -y install graphviz-devel graphviz-python ImageMagick postgis2_96 &&\
    yum -y install freetype-devel libpng-devel giflib-devel libjpeg-devel gd-devel proj-devel &&\
    yum -y install proj-nad proj-epsg libxml2-devel libxslt-devel pam-devel &&\
    yum -y install python-psycopg2 libpqxx-devel hdf hdf-devel freetds-devel postgresql-devel &&\
    yum -y install gdal-python mapserver mapserver-python libxml2 libxml2-python python-lxml python-pip python-devel gcc mlocate &&\
    yum -y install scipy blas blas-devel lapack lapack-devel lvm2 firefox cachefilesd &&\
    yum -y groups install "GNOME Desktop" &&\
    yum -y install fftw-devel motif-devel ghc-OpenGL-devel


# For InstantReality's aopt command referenced in doc/instructions/SPATIAL_3d.md
RUN yum -y install freeglut luajit
#RUN wget http://doc.instantreality.org/media/uploads/downloads/2.8.0/InstantReality-RedHat-7-x64-2.8.0.38619.rpm &&\
#    rpm -Uvh InstantReality-RedHat-7-x64-2.8.0.38619.rpm

# Build and install MB-System
RUN wget -q -N ftp://ftp.ldeo.columbia.edu/pub/MB-System/mbsystem-5.5.2284.tar.gz &&\
    tar -xzf mbsystem-5.5.2284.tar.gz &&\
    cd mbsystem-5.5.2284/ &&\
    ./configure --with-otps-dir=/usr/local/OTPS2 &&\
    make -j 2 && make install &&\
    cd ..

COPY requirements     /opt/stoqsgit/requirements/

RUN /bin/bash -c '\
    export PATH=/usr/pgsql-9.6/bin:/usr/bin:\$PATH ;\
    export LD_PRELOAD=/usr/lib64/libgdal.so.1 ;\
    cd /opt/stoqsgit ;\
    pip3.6 install -r requirements/production.txt'

# Required for plotting basemap in LRAUV plots
RUN /bin/bash -c '\
    cd /tmp \n\
    export PATH=/usr/pgsql-9.6/bin:/usr/bin:\$PATH ;\
    wget http://sourceforge.net/projects/matplotlib/files/matplotlib-toolkits/basemap-1.0.7/basemap-1.0.7.tar.gz ;\
    tar -xzf basemap-1.0.7.tar.gz ;\
    cd /tmp/basemap-1.0.7 ;\
    export GEOS_DIR=/usr/local ;\
    python3.6 setup.py install ;\
    \
    cd /tmp ;\
    wget http://sourceforge.net/projects/matplotlib/files/matplotlib-toolkits/natgrid-0.2/natgrid-0.2.1.tar.gz ;\
    tar -xzf natgrid-0.2.1.tar.gz ;\
    cd /tmp/natgrid-0.2.1 ;\
    python3.6 setup.py install'


# Build database for locate command
# (updatedb/locate are not included in base centos:7 image)
RUN yum -y install mlocate &&\
    updatedb

CMD ["nginx", "-g", "daemon off;"]
