#
# This was an initial attempt building MapServer itself (as indicated in provision.sh)
# on top our the base image.
# But we are now trying to use an already exisiting MapServer image. See README.
#

FROM mbari/stoqs-base:0.0.1

# TODO Mapserver should probably be in its own image so it can be launched separately.
# Build and install Mapserver
RUN wget -q -N http://download.osgeo.org/mapserver/mapserver-6.4.1.tar.gz &&\
    tar xzf mapserver-6.4.1.tar.gz &&\
    cd mapserver-6.4.1 &&\
    mkdir build &&\
    cd build &&\
    /opt/cmake/bin/cmake .. -DWITH_FRIBIDI=0 -DWITH_CAIRO=0 -DWITH_FCGI=0 -DCMAKE_PREFIX_PATH="/usr/local;/usr/pgsql-9.6" &&\
    make -j 2 && make install &&\
    cp /usr/local/bin/mapserv /var/www/cgi-bin &&\
    ldconfig &&\
    cp /etc/sysconfig/httpd /etc/sysconfig/httpd.bak &&\
    echo -e "\
# Needed for mapserv in /var/www/cgi-bin\n\
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib64\n\
export LD_LIBRARY_PATH\n" >> /etc/sysconfig/httpd &&\
    cd ../.. &&\
    touch /tmp/mapserver_stoqshg.log &&\
    chown apache.apache /tmp/mapserver_stoqshg.log &&\
    chmod go+w /tmp/mapserver_stoqshg.log

ADD run-httpd.sh /usr/bin/

# TODO httpd volumes (data, logs..)

ENTRYPOINT ["/usr/bin/run-httpd.sh"]
CMD []
