#!/bin/bash
# The working directory in docker cloud is $STOQS_HOME/docker
echo "Parent of PWD directory listing"
ls -l $(dirname `pwd`)
echo "PWD listing"
ls -l 
echo "env:"
env
# Use /src/${BUILD_CODE} for STOQS_HOME in docker-compose.test.yml
docker-compose -f docker-compose.test.yml build
