#!/bin/bash
# Use /src/${BUILD_CODE} for STOQS_HOME in docker-compose.test.yml
# The working directory for this script in docker cloud is $STOQS_HOME/docker

echo "==> hooks/build"
echo "*** Parent of PWD directory listing"
ls -l $(dirname `pwd`)
echo "*** PWD listing"
ls -l 

echo "*** rm /tmp/docker_stoqs_vols"
rm /tmp/docker_stoqs_vols

echo "*** docker-compose -f docker-compose.test.yml build"
docker-compose -f docker-compose.test.yml build

echo "*** docker-compose -f docker-compose.test.yml up -d"
docker-compose -f docker-compose.test.yml up -d

# Wait for test.sh to start, then check that it finishes before stopping the services
ps -ef | grep test.sh | grep -v grep
while [[ $? == 1 ]] ; do
    sleep 30; echo "*** Waiting for test.sh to start ..."
    ps -ef | grep test.sh | grep -v grep
done
while [[ $? == 0 ]] ; do
    sleep 30; echo "*** Waiting for test.sh to complete ..."
    ps -ef | grep test.sh | grep -v grep
done

echo "*** docker-compose stop"
docker-compose stop
