#!/bin/bash
# Check for running server and completed test.sh then stop services

echo "==> hooks/post_test"
ps -ef | grep test.sh | grep -v grep
while [[ $? != 1 ]] ; do
    sleep 30; echo "*** Waiting for test.sh to complete ..."
    ps -ef | grep test.sh | grep -v grep
done
echo "*** docker-compose stop"
docker-compose stop
