#!/bin/bash
# Use /src/${BUILD_CODE} for STOQS_HOME in docker-compose.test.yml
# The working directory for this script in docker cloud is $STOQS_HOME/docker

echo "==> hooks/test"
echo "*** env"
env
# Wait for test.sh to start, then check that it finishes before stopping the services
ps -ef | grep test.sh | grep -v grep
while [[ $? == 1 ]] ; do
    sleep 30; echo "*** Waiting for test.sh to start ..."
    ps -ef | grep test.sh | grep -v grep
done
while [[ $? == 0 ]] ; do
    sleep 30; echo "*** Waiting for test.sh to complete ..."
    ps -ef | grep test.sh | grep -v grep
done

echo "*** docker-compose stop"
docker-compose stop
