#!/bin/bash
# Use /src/${BUILD_CODE} for STOQS_HOME in docker-compose.test.yml
# The working directory for this script in docker cloud is $STOQS_HOME/docker

echo "==> hooks/test"

echo "*** docker-compose -f docker-compose.test.yml up -d"
docker-compose -f docker-compose.test.yml up -d

# Wait for test.sh to start, then check that it finishes before stopping the services
docker exec stoqs ps -ef | grep test.sh | grep -v grep
while [[ $? == 1 ]] ; do
    sleep 30; echo "*** Waiting for test.sh to start ..."
    docker exec stoqs ps -ef | grep test.sh | grep -v grep
done

docker exec stoqs ps -ef | grep test.sh | grep -v grep
while [[ $? == 0 ]] ; do
    sleep 30; echo "*** Waiting for test.sh to complete ..."
    docker exec stoqs ps -ef | grep test.sh | grep -v grep
done

echo "*** docker-compose -f docker-compose.test.yml logs"
docker-compose -f docker-compose.test.yml logs

echo "*** docker-compose -f docker-compose.test.yml stop"
docker-compose -f docker-compose.test.yml stop
