# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


from . import trex_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='trex_sensor.proto',
  package='org.mbari.trex',
  serialized_pb='\n\x11trex_sensor.proto\x12\x0eorg.mbari.trex\x1a\ntrex.proto\"\xe1\x03\n\rSensorMessage\x12\x34\n\x06sample\x18\x02 \x03(\x0b\x32$.org.mbari.trex.SensorMessage.Sample\x12\x37\n\x07gps_fix\x18\x01 \x01(\x0b\x32&.org.mbari.trex.SensorMessage.GpsError\x12/\n\x0cobservations\x18\x03 \x03(\x0b\x32\x19.org.mbari.trex.Predicate\x1a\xa2\x01\n\x06Sample\x12\r\n\x05utime\x18\x01 \x02(\x04\x12\x10\n\x08northing\x18\x02 \x02(\x02\x12\x0f\n\x07\x65\x61sting\x18\x03 \x02(\x02\x12\r\n\x05\x64\x65pth\x18\x04 \x02(\x02\x12\x13\n\x0btemperature\x18\x05 \x01(\x02\x12\x10\n\x08salinity\x18\x06 \x01(\x02\x12\x0f\n\x07nitrate\x18\x07 \x01(\x02\x12\x11\n\tgulper_id\x18\x08 \x01(\x05\x12\x0c\n\x04\x63hfl\x18\t \x01(\x02\x1a\x8a\x01\n\x08GpsError\x12\x11\n\tfrom_time\x18\x01 \x02(\x04\x12\x0f\n\x07to_time\x18\x02 \x02(\x04\x12\x10\n\x08northing\x18\x03 \x01(\x02\x12\x0f\n\x07\x65\x61sting\x18\x04 \x01(\x02\x12\x1b\n\x13northing_error_rate\x18\x07 \x01(\x02\x12\x1a\n\x12\x65\x61sting_error_rate\x18\x08 \x01(\x02')




_SENSORMESSAGE_SAMPLE = descriptor.Descriptor(
  name='Sample',
  full_name='org.mbari.trex.SensorMessage.Sample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='utime', full_name='org.mbari.trex.SensorMessage.Sample.utime', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='northing', full_name='org.mbari.trex.SensorMessage.Sample.northing', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='easting', full_name='org.mbari.trex.SensorMessage.Sample.easting', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='depth', full_name='org.mbari.trex.SensorMessage.Sample.depth', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='temperature', full_name='org.mbari.trex.SensorMessage.Sample.temperature', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='salinity', full_name='org.mbari.trex.SensorMessage.Sample.salinity', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='nitrate', full_name='org.mbari.trex.SensorMessage.Sample.nitrate', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='gulper_id', full_name='org.mbari.trex.SensorMessage.Sample.gulper_id', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='chfl', full_name='org.mbari.trex.SensorMessage.Sample.chfl', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=228,
  serialized_end=390,
)

_SENSORMESSAGE_GPSERROR = descriptor.Descriptor(
  name='GpsError',
  full_name='org.mbari.trex.SensorMessage.GpsError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='from_time', full_name='org.mbari.trex.SensorMessage.GpsError.from_time', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='to_time', full_name='org.mbari.trex.SensorMessage.GpsError.to_time', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='northing', full_name='org.mbari.trex.SensorMessage.GpsError.northing', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='easting', full_name='org.mbari.trex.SensorMessage.GpsError.easting', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='northing_error_rate', full_name='org.mbari.trex.SensorMessage.GpsError.northing_error_rate', index=4,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='easting_error_rate', full_name='org.mbari.trex.SensorMessage.GpsError.easting_error_rate', index=5,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=393,
  serialized_end=531,
)

_SENSORMESSAGE = descriptor.Descriptor(
  name='SensorMessage',
  full_name='org.mbari.trex.SensorMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sample', full_name='org.mbari.trex.SensorMessage.sample', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='gps_fix', full_name='org.mbari.trex.SensorMessage.gps_fix', index=1,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='observations', full_name='org.mbari.trex.SensorMessage.observations', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SENSORMESSAGE_SAMPLE, _SENSORMESSAGE_GPSERROR, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=50,
  serialized_end=531,
)

_SENSORMESSAGE_SAMPLE.containing_type = _SENSORMESSAGE;
_SENSORMESSAGE_GPSERROR.containing_type = _SENSORMESSAGE;
_SENSORMESSAGE.fields_by_name['sample'].message_type = _SENSORMESSAGE_SAMPLE
_SENSORMESSAGE.fields_by_name['gps_fix'].message_type = _SENSORMESSAGE_GPSERROR
_SENSORMESSAGE.fields_by_name['observations'].message_type = trex_pb2._PREDICATE
DESCRIPTOR.message_types_by_name['SensorMessage'] = _SENSORMESSAGE

class SensorMessage(message.Message, metaclass=reflection.GeneratedProtocolMessageType):
  class Sample(message.Message, metaclass=reflection.GeneratedProtocolMessageType):
    DESCRIPTOR = _SENSORMESSAGE_SAMPLE
    
    # @@protoc_insertion_point(class_scope:org.mbari.trex.SensorMessage.Sample)
  
  class GpsError(message.Message, metaclass=reflection.GeneratedProtocolMessageType):
    DESCRIPTOR = _SENSORMESSAGE_GPSERROR
    
    # @@protoc_insertion_point(class_scope:org.mbari.trex.SensorMessage.GpsError)
  DESCRIPTOR = _SENSORMESSAGE
  
  # @@protoc_insertion_point(class_scope:org.mbari.trex.SensorMessage)

# @@protoc_insertion_point(module_scope)
